from django.db import models

# Create your models here.
class Location(models.Model):
    id = models.AutoField(primary_key=True)
    locationName = models.CharField(max_length=250, unique=True)
    class Meta:
        ordering = ('locationName',)
    def __str__(self):
        return '{}'.format(self.locationName)
class Est_Report(models.Model):
    id = models.AutoField(primary_key=True)
    EMP_NO = models.IntegerField(default=0,unique=True)
    SGID = models.CharField(max_length=250)
    EMP_NAME = models.CharField(max_length=250, unique=False)
    CADRE = models.CharField(max_length=250, default= 'NON-CADRE')
    GENDER = models.CharField(max_length=250)
    GRADE = models.CharField(max_length=250)
    DESIGNATION = models.CharField(max_length=250, unique=False)
    LOCATION_CATEGORY = models.CharField(max_length=250, unique=False)
    LOCATION = models.CharField(max_length=250, unique=False)
    REGION = models.CharField(max_length=250, blank=True)
    TEAM = models.CharField(max_length=250, blank=True)
    SIF_Class = models.CharField(max_length=250, blank=True)
    SIF_SUBCLASS = models.CharField(max_length=250, blank=True)
    SIF_CATEGORY = models.CharField(max_length=250, blank=True)
    SIF_LOCATION = models.CharField(max_length=250, blank=True)
    WORKSTATUS = models.CharField(max_length=250, blank=True)
    DOB = models.DateTimeField(auto_now_add=False,blank=True)
    DOJ = models.DateTimeField(auto_now_add=False,blank=True)
    GROUP_DOJ = models.CharField(max_length=250, blank=True)
    DOR = models.CharField(max_length=250, blank=True)
    SEPARATION_Date = models.CharField(max_length=250, blank=True)
    AGE = models.IntegerField(default=0)
    POSITION_NUMBER = models.CharField(max_length=250, unique=False)
    Position_Description = models.CharField(max_length=250, blank=True)
    COST_CENTER = models.CharField(max_length=250, blank=True)
    SIF_ENTITY = models.CharField(max_length=250, blank=True)
    LEVEL1 = models.CharField(max_length=250, blank=True)
    LEVEL2 = models.CharField(max_length=250, blank=True)
    LEVEL3 = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ('EMP_NO',)
    def __str__(self):
        return '{}'.format(self.EMP_NO)


class Est_Report_all(models.Model):
    # id = models.AutoField(primary_key=True)
    EMP_NO = models.IntegerField(default=0,unique=False)
    SGID = models.CharField(max_length=250)
    EMP_NAME = models.CharField(max_length=250, unique=False)
    CADRE = models.CharField(max_length=250, default= 'NON-CADRE')
    GENDER = models.CharField(max_length=250)
    GRADE = models.CharField(max_length=250)
    DESIGNATION = models.CharField(max_length=250, unique=False)
    LOCATION_CATEGORY = models.CharField(max_length=250, unique=False)
    LOCATION = models.CharField(max_length=250, unique=False)
    REGION = models.CharField(max_length=250, blank=True)
    TEAM = models.CharField(max_length=250, blank=True)
    SIF_Class = models.CharField(max_length=250, blank=True)
    SIF_SUBCLASS = models.CharField(max_length=250, blank=True)
    SIF_CATEGORY = models.CharField(max_length=250, blank=True)
    SIF_LOCATION = models.CharField(max_length=250, blank=True)
    WORKSTATUS = models.CharField(max_length=250, blank=True)
    DOB = models.DateTimeField(auto_now_add=False,blank=True)
    DOJ = models.DateTimeField(auto_now_add=False,blank=True)
    GROUP_DOJ = models.CharField(max_length=250, blank=True)
    DOR = models.CharField(max_length=250, blank=True)
    SEPARATION_Date = models.CharField(max_length=250, blank=True)
    AGE = models.IntegerField(default=0)
    POSITION_NUMBER = models.CharField(max_length=250, unique=False)
    Position_Description = models.CharField(max_length=250, blank=True)
    COST_CENTER = models.CharField(max_length=250, blank=True)
    SIF_ENTITY = models.CharField(max_length=250, blank=True)
    LEVEL1 = models.CharField(max_length=250, blank=True)
    LEVEL2 = models.CharField(max_length=250, blank=True)
    LEVEL3 = models.CharField(max_length=250, blank=True)